from ..parser.rule_parser import Rule, RuleSet


class LispGenerator:
    def generate(self, ruleset: RuleSet) -> str:
        lines = [f";; Generated by pid-engine v{ruleset.version}"]
        for rule in ruleset.rules:
            lines.append(self._rule_to_lisp(rule))
        return "\n\n".join(lines)

    def _rule_to_lisp(self, rule: Rule) -> str:
        params = " ".join(rule.params.keys()) if rule.params else ""
        body = self._body_to_lisp(rule.body)
        return f"(defun {rule.name} ({params})\n  {body})"

    def _body_to_lisp(self, body: list) -> str:
        if not body:
            return "nil"
        exprs = [self._expr_to_lisp(expr) for expr in body]
        return "\n  ".join(exprs)

    def _expr_to_lisp(self, expr) -> str:
        if isinstance(expr, str):
            return expr
        if isinstance(expr, (int, float)):
            return str(expr)
        if isinstance(expr, bool):
            return "t" if expr else "nil"
        if isinstance(expr, list):
            inner = " ".join(self._expr_to_lisp(e) for e in expr)
            return f"({inner})"
        if isinstance(expr, dict):
            op = expr.get("op", "progn")
            args = expr.get("args", [])
            inner = " ".join(self._expr_to_lisp(a) for a in args)
            return f"({op} {inner})"
        return str(expr)
